---
abstract: 'A simple interface to the EchoNest API'
author:
  - 'Nick Langridge <nickl@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-EchoNest
requires:
  JSON::XS::VersionOneAndTwo: 0
  LWP::UserAgent: 0
  Moose: 0
  MooseX::StrictConstructor: 0
  URI::QueryParam: 0
resources:
  repository: https://github.com/nicklangridge/WebService-EchoNest
version: 0.005
